### PR TITLE
add new rubygems password/emailaddr

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
README also needs a change: https://github.com/voxpupuli/plumbing#setting-up-a-gem-for-rubygems-deploys.

This also looks like you're removing the credentials file altogether?

**Comment by bastelfreak** [comment]
ah lol, good catch.

**Review by ekohl — APPROVED** [review]
Note to self: https://gist.github.com/marceloalmeida/e6593b93b388cdf1dbc282dffd424d1b makes reviewing this much easier. On the console the output of `git diff` becomes useful.

**Comment by ekohl** [comment]
Also, apologies for not getting to this sooner. I also verified I could log in on rubygems.org with these new credentials.

**Pull request merged**
