### PR TITLE
Nominate Nate McCurdy

### PR DESCRIPTION
**Pull request by natemccurdy**
I'd like to join the community 👍

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @natemccurdy, thanks for the submission! Do you have a gpg key? We normally require gpg signed commits to this repo, mostly because we also handle our secrets with it.

**Comment by natemccurdy** [comment]
@bastelfreak I do. I'll sign and re-commit shortly.

**Comment by natemccurdy** [comment]
@bastelfreak Signed and rebased.

**Comment by alexjfisher** [comment]
@natemccurdy You might want to participate in some pgp key exchanges.  Other PMC members will need a trust path to you.

**Comment by alexjfisher** [comment]
@natemccurdy Hi!  We don't all need to have signed each other's keys, but we do all need a reasonable trust path to each other.  Am I right in thinking you're still based in Portland?  Perhaps you could do a key exchange with @binford2k? (@bastelfreak and myself can do the same with Ben at [cfgmgmt camp](https://cfgmgmtcamp.eu) in about 6 weeks time.)

**Pull request merged**
