### PR TITLE
Add puppet-openvmtools to share/modules

### PR DESCRIPTION
**Pull request by cdenneen**
@razorsedge

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @cdenneen. We should wait with merging this until @razorsedge agrees on the migration.

**Comment by cdenneen** [comment]
I’ve been trying. Thanks

**Comment by cdenneen** [comment]
Still waiting

**Comment by bastelfreak** [comment]
Hi. This is replaced by https://github.com/voxpupuli/plumbing/pull/209

**Pull request closed without merging**
