### PR TITLE
We now have puppet-yum

### PR DESCRIPTION
**Pull request by jyaworski**
@bastelfreak

### CODE REVIEW

**Comment by igalic** [comment]
how did that happen?

**Comment by jyaworski** [comment]
https://github.com/CERIT-SC/puppet-yum/issues/14

**Comment by jonhattan** [comment]
Still no release in the forge.

**Comment by vholer** [comment]
Hi guys, can you please relase the module on PF so that people are not confused?  I think there doesn't have to be much changes for initial release... Anything for start is better than nothing. Thanks a lot <3

**Comment by jyaworski** [comment]
@vholer releasing was broken until recently. We look to get this out today.

**Comment by vholer** [comment]
Thanks!

**Pull request merged**
